### ISSUE TITLE
The issue of reproducing LRR

### ISSUE THREAD

**Issue by happy-Moer** [baoguangsheng/fast-detect-gpt#11]
I attempted to reproduce the performance of baselines on the ChatGPT-generated PubMed dataset. I discovered that the LRR (Neo-2.7) result reported in the paper is 0.7433, as shown in the figure below. However, the result I obtained using the code you provided is 0.5980. I wonder if there is any problem with my experiment.

![屏幕截图 2024-05-07 132851](https://github.com/baoguangsheng/fast-detect-gpt/assets/77430746/f25014f6-8f2b-4e17-8f54-97cef7ed3294)
![屏幕截图 2024-05-07 132925](https://github.com/baoguangsheng/fast-detect-gpt/assets/77430746/a62aae90-b6e6-4f2c-a9ed-d39fb6abfd10)

**Comment by baoguangsheng** [comment]
As your log shows, you were running Rank baseline but not LRR.

**Comment by happy-Moer** [comment]
In baselines.py, include
criterion_fns = {'likelihood': get_likelihood,
                      'rank': get_rank,
                      'logrank': get_logrank,
                      'entropy': get_entropy}
Among them, logrank refers to LogRank. I did not see 'lrr', only 'rank'. What does 'rank' refer to in the paper?

**Comment by baoguangsheng** [comment]
You can find LRR in detect_llm.py. The baselines.py only contains the very basic statistical methods, where the 'rank' refers to the averaged Rank value of the tokens.
