### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by wellmslouis** [baoguangsheng/fast-detect-gpt#17]
您好，感谢您的工作！我在阅读代码的时候遇到了一些困惑：
在`fast_detect-gpt.py`文件中，函数`get_sampling_discrepancy`和`get_sampling_discrepancy_analytic`的使用场景区别是什么？（采样与不采样的区别吗？）
我观察到`local_infer.py`文件这个本地交互演示默认并没有调用前者，这会对本地的计算结果产生影响吗？

**Comment by baoguangsheng** [comment]
您好！很高兴您对我们的工作感兴趣！
函数get_sampling_discrepancy和get_sampling_discrepancy_analytic是Fast-DetectGPT的两个不同实现。实际使用中建议使用后者，会比前者快10%左右。前者是Fast-DetectGPT一个直观实现，比较符合直觉，也容易理解，但只是一个采样近似。后者是对前者进行理论分析后，理论推导的结果，是一个解析解，效率更高，理论上来说也更准确（实际上差不多）。从便于理解的角度，先理解前者的原理，以此为基础，再理解后者会容易一些。
希望对您有帮助！

祝好，
光胜

________________________________
From: wellmslouis ***@***.***>
Sent: Monday, July 8, 2024 11:54 AM
To: baoguangsheng/fast-detect-gpt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [baoguangsheng/fast-detect-gpt] Code question (Issue #17)


您好，感谢您的工作！我在阅读代码的时候遇到了一些困惑：
在fast_detect-gpt.py文件中，函数get_sampling_discrepancy和get_sampling_discrepancy_analytic的使用场景区别是什么？（采样与不采样的区别吗？）
我观察到local_infer.py文件这个本地交互演示默认并没有调用前者，这会对本地的计算结果产生影响吗？

―

**Comment by wellmslouis** [comment]
感谢您的解答！我也在论文附录B找到了对应说明。
祝您工作顺利！
