### ISSUE TITLE
你好，怎么复现你们http://region-9.autodl.pro:21504/#/show上面的测评结果呀

### ISSUE THREAD

**Issue by Eleanor456** [baoguangsheng/fast-detect-gpt#18]
你好，很感谢你们开源了如此优秀的工作，我在使用过程中发现有一些数据本地测评的结果跟线上版本不一致，尤其是中文数据，使用GPT-NEO-2.7b会报如下问题：
328 CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

请问一下，如何复现跟在线demo一样的结果呢？需要调整模型还是修改local_infer_ref文件中的内容呢？

**Comment by baoguangsheng** [comment]
您好！测试结果和线上不一致的文本可否提供几个？我来测试对比一下。谢谢！

从你的CUDA error来看是触发了一些assert，可能是一些极端情况导致的越界。有没有exception的call stack我看看?

**Comment by Eleanor456** [comment]
> 您好！测试结果和线上不一致的文本可否提供几个？我来测试对比一下。谢谢！
> 
> 从你的CUDA error来看是触发了一些assert，可能是一些极端情况导致的越界。有没有exception的call stack我看看?

你好，我发现assert是中文文字较长导致的。

而且，在测试中发现，Qwen1.8b相较于GPT-Neo-2.7b，会带来更高的误报，根据论文理解，模型类型应该不影响结果，请问一下这里是为什么呢？对模型的选取应该遵循什么样的规则呢

**Comment by baoguangsheng** [comment]
模型会影响结果的。而且，local_infer.py和线上demo都是依据local_infer_ref文件夹下的Neo-2.7B的测试结果来估算probability的。如果你将打分模型替换为Qwen1.8b，相应的local_infer_ref下的文件也应该更新为Qwen1.8b测试的结果，否则两者不匹配，估算的概率就不准确了。

**Comment by Eleanor456** [comment]
好的，感谢






------------------ 原始邮件 ------------------
发件人: Guangsheng Bao ***@***.***&gt;
发送时间: 2024年7月16日 17:23
收件人: baoguangsheng/fast-detect-gpt ***@***.***&gt;
抄送: Eleanor456 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [baoguangsheng/fast-detect-gpt] 你好，怎么复现你们http://region-9.autodl.pro:21504/#/show上面的测评结果呀 (Issue #18)





 
模型会影响结果的。而且，local_infer.py和线上demo都是依据local_infer_ref文件夹下的Neo-2.7B的测试结果来估算probability的。如果你将打分模型替换为Qwen1.8b，相应的local_infer_ref下的文件也应该更新为Qwen1.8b测试的结果，否则两者不匹配，估算的概率就不准确了。
