### ISSUE TITLE
请教一下，我使用GPT生成的中文数据集进行测试时，无法准确鉴别

### ISSUE THREAD

**Issue by xuanyuc** [baoguangsheng/fast-detect-gpt#23]
请教一下，我使用GPT生成的中文数据集进行测试时，无法准确识别分类结果。
我选取的模型都是gpt2，但是无论是human或者gpt的句子，普遍都是较低的Ai率。
请问，是因为gpt2模型效果太差了吗？要替换其他更大的模型？
还是说，fast-detect-gpt适用英文，但对中文的识别能力不太行？

**Comment by baoguangsheng** [comment]
Fast-detect-gpt和语言无关，在具体语言上的效果依赖于使用的LLM。

gpt2的训练数据主要是英文，中文没测过，但应该很差。建议使用gpt-neo-2.7B或者gpt-j。

**Comment by xuanyuc** [comment]
> Fast-detect-gpt和语言无关，在具体语言上的效果依赖于使用的LLM。
> 
> gpt2的训练数据主要是英文，中文没测过，但应该很差。建议使用gpt-neo-2.7B或者gpt-j。

谢谢您的解答。
因为服务器没法连接外网，TF上无法下载，我在魔搭社区上只找到了gpt-j，但是服务器上卡只有30G的显存。
我是看了您的论文后有所启发，写了一个零样本的中文的Ai检测算法，想测试一下fast-detectgpt的中文检测效果。目前我的实验在HC3-chinese数据集上AUROC的值能达到0.96，想请教一下，这个数据算优秀吗，能否达到SOAP的标准。
另外做比对实验的时候，感觉国内外几乎没有做中文的检测，同样大模型生成的中文数据集也很少，请问您在这方面有什么建议吗？
谢谢指点

**Comment by baoguangsheng** [comment]
一般来说，AUROC达到0.96是一个不错的检测准确率了。具体需要和同类方法对比。

中文的检测工作比较少，可以系统的搜索一下。

**Comment by xuanyuc** [comment]
> 一般来说，AUROC达到0.96是一个不错的检测准确率了。具体需要和同类方法对比。
> 
> 中文的检测工作比较少，可以系统的搜索一下。

好的，谢谢您！
