### ISSUE TITLE
Explanation of the division in equation (3)

### ISSUE THREAD

**Issue by ziyingsk** [baoguangsheng/fast-detect-gpt#3]
Dear Mr. Bao

I wish you a happy new year!
Regarding to your paper about "Fast-DetectGpt", Could you please explain the reason why you divided the standard deviation of the condition probability caused by perturbation in Equation (3)?

Kindly regards,

**Comment by ziyingsk** [comment]
Now I see the reason. you actually talke about the reason later in the paper at section 3.2. I think it would be better to mention it directly after you give equation (3).

**Comment by ziyingsk** [comment]
Of course it is a good reason when dividing the standard deviation increase 10% of the performance. Still, the true reason behind the phenomenon should lay in the distribution of (log pθ(˜x|x) − ˜μ) within one sample. Anyway, good job!

**Comment by baoguangsheng** [comment]
Thank you for providing your feedback! In our upcoming revision, we will take into account including the rationale within the context of equation 3. Wishing you a joyful New Year!
