### ISSUE TITLE
How to detect directly on a single text?

### ISSUE THREAD

**Issue by WangRongsheng** [baoguangsheng/fast-detect-gpt#8]
Hi, I have a piece of text. How should I input it to Fast-DetectGPT instead of using the default JSON file?

**Comment by Jacobsonradical** [comment]
If you only have one piece of text, I believe that they have the interactive shell mode for you to directly get the probability.

**Comment by Jacobsonradical** [comment]
> Hi, I have a piece of text. How should I input it to Fast-DetectGPT instead of using the default JSON file?

If you only have one piece of text, I believe that they have the interactive shell mode for you to directly get the probability.

**Comment by baoguangsheng** [comment]
Yes. We have the interactive local demo "scripts/local_infer.py", where you can input the text and obtain detection results.

**Comment by WangRongsheng** [comment]
> Yes. We have the interactive local demo "scripts/local_infer.py", where you can input the text and obtain the detection result.

thanks, i will test it.

**Comment by WangRongsheng** [comment]
Hi, Do different `dataset` have an effect on detection?

```python
parser.add_argument('--dataset', type=str, default="xsum")
```

**Comment by baoguangsheng** [comment]
It will not affect the detection of the local demo. Just some legacy code.

**Comment by WangRongsheng** [comment]
> It will not affect the detection of the local demo. Just some legacy code.

thank you.
